const express = require('express');
const {createOrder,getMyOrders,getAllOrders,updateOrderStatus} = require('../controllers/orderController');
const protect = require('../middleware/authMiddleware');
const adminOnly = require("../middleware/adminMiddleware");
const router = express.Router();
router.post('/',protect,createOrder);
router.get('/myorders',protect,getMyOrders);
router.put("/:id/status",protect,adminOnly,updateOrderStatus);
router.get('/',protect,adminOnly,getAllOrders);
module.exports = router;